-- ============================================================
-- Migration: 008_team_accounts.sql
-- Description: Team account management system — full schema.
--
-- STATUS: ✅ VERIFIED LIVE — Tue Mar 17, 2026
--
-- Execution history:
--   - profiles.username, profiles.is_active, role constraint
--     expansion, invite_tokens, pending_registrations, and
--     password_reset_requests were applied manually via
--     Supabase SQL Editor and confirmed live.
--   - This file reflects the final executed schema for the
--     audit record. Do NOT re-run — all objects already exist.
--
-- To verify at any time:
--   SELECT column_name FROM information_schema.columns
--   WHERE table_name = 'profiles'
--   AND column_name IN ('username','is_active');
--
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public'
--   AND table_name IN (
--     'invite_tokens','pending_registrations','password_reset_requests'
--   );
-- ============================================================


-- ── SECTION 1: PROFILES — NEW COLUMNS ───────────────────────

-- username: unique per staff member, used in place of email for login
-- NULL for students/members who self-register with a real email
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS username text UNIQUE;

-- is_active: Owner/Manager sets false to revoke access immediately
-- Middleware checks user_metadata.is_active on every request
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;


-- ── SECTION 2: PROFILES — EXPANDED ROLE CONSTRAINT ──────────

-- Keeps all existing roles + adds manager, receptionist, social_media
-- admin is preserved — existing Admin Dashboard is unaffected
ALTER TABLE profiles
  DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN (
    'owner',
    'admin',          -- existing — Admin Dashboard untouched
    'manager',        -- new — manages teachers, social_media, members
    'receptionist',   -- new — front desk, bookings
    'teacher',        -- existing — Teacher Dashboard
    'social_media',   -- new — content team (Phase 3 dashboard)
    'student',        -- existing — Student Dashboard
    'member'          -- existing — Member Dashboard
  ));


-- ── SECTION 3: UPDATE PROFILE TRIGGER ───────────────────────

-- Replaces handle_new_user() from 003_profiles_members.sql
-- Now also maps is_active from user metadata on account creation
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO profiles (id, email, full_name, role, is_active)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'role', 'student'),
    COALESCE((NEW.raw_user_meta_data->>'is_active')::boolean, true)
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ── SECTION 4: PROFILES — NEW RLS POLICIES ──────────────────

-- Owner has full access to all profiles
CREATE POLICY "profiles_owner_all"
  ON profiles FOR ALL
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'owner'
  );

-- Manager can read all profiles (needed to manage their team)
CREATE POLICY "profiles_manager_read"
  ON profiles FOR SELECT
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'manager'
  );

-- Manager can update profiles of roles they manage (not owner/manager)
CREATE POLICY "profiles_manager_update"
  ON profiles FOR UPDATE
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'manager'
    AND role NOT IN ('owner', 'manager')
  );


-- ── SECTION 5: INVITE_TOKENS ─────────────────────────────────
-- One row per invite link generated by a Manager.
-- Token is embedded in: /register?token=<token>
-- Single-use, 7-day expiry.

CREATE TABLE IF NOT EXISTS invite_tokens (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Random 64-char hex token embedded in the invite URL
  token         text UNIQUE NOT NULL
                DEFAULT encode(gen_random_bytes(32), 'hex'),

  -- Role this invite unlocks — person cannot change this
  invited_role  text NOT NULL
                CHECK (invited_role IN ('teacher', 'social_media', 'member')),

  -- Manager who generated this token
  created_by    uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Optional label so Manager remembers who this was for
  invite_note   text,

  -- One-time use
  used          boolean NOT NULL DEFAULT false,
  used_at       timestamptz,

  -- Link dies after 7 days
  expires_at    timestamptz NOT NULL DEFAULT now() + interval '7 days',

  created_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE invite_tokens ENABLE ROW LEVEL SECURITY;

-- Manager can generate tokens
CREATE POLICY "invite_tokens_manager_insert"
  ON invite_tokens FOR INSERT
  WITH CHECK (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'manager'
    AND auth.uid() = created_by
  );

-- Manager and Owner can view tokens
CREATE POLICY "invite_tokens_manager_read"
  ON invite_tokens FOR SELECT
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') IN ('manager', 'owner')
  );

-- Manager can delete their own unused tokens (revoke an invite)
CREATE POLICY "invite_tokens_manager_delete"
  ON invite_tokens FOR DELETE
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'manager'
    AND auth.uid() = created_by
    AND used = false
  );

-- Public SELECT needed for token validation on the signup page
-- (API routes use service role but this covers direct queries)
CREATE POLICY "invite_tokens_public_validate"
  ON invite_tokens FOR SELECT
  USING (true);


-- ── SECTION 6: PENDING_REGISTRATIONS ────────────────────────
-- Holds signup form submissions until Manager approves or rejects.
-- On approval: API creates Supabase auth user + profile row,
--              deletes password_temp, updates status.
-- On rejection: row stays with status='rejected' for audit trail.

CREATE TABLE IF NOT EXISTS pending_registrations (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Personal info entered by the applicant
  full_name        text NOT NULL,
  email            text NOT NULL,
  phone            text,

  -- Login credentials chosen by the applicant
  username         text NOT NULL,

  -- Temporary until approval. Nulled out after auth user is created.
  password_temp    text NOT NULL,

  -- Role comes from the invite token — applicant cannot change it
  requested_role   text NOT NULL
                   CHECK (requested_role IN ('teacher', 'social_media', 'member')),

  -- The invite token that was used to access the signup form
  invite_token_id  uuid REFERENCES invite_tokens(id) ON DELETE SET NULL,

  -- The Manager who owns this approval queue item
  manager_id       uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Review state
  status           text NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'approved', 'rejected')),

  reviewed_by      uuid REFERENCES profiles(id) ON DELETE SET NULL,
  reviewed_at      timestamptz,
  rejection_reason text,

  created_at       timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE pending_registrations ENABLE ROW LEVEL SECURITY;

-- Manager sees their own queue
CREATE POLICY "pending_reg_manager_read"
  ON pending_registrations FOR SELECT
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'manager'
    AND auth.uid() = manager_id
  );

-- Owner can see all
CREATE POLICY "pending_reg_owner_read"
  ON pending_registrations FOR SELECT
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'owner'
  );

-- Manager can approve/reject their queue
CREATE POLICY "pending_reg_manager_update"
  ON pending_registrations FOR UPDATE
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'manager'
    AND auth.uid() = manager_id
  );

-- Inserts handled by API route with service role key only


-- ── SECTION 7: PASSWORD_RESET_REQUESTS ──────────────────────
-- Staff forgot-password requests go here first.
-- Manager approves → system sends Supabase password reset email
-- to the staff member's registered email address.
-- Students bypass this — they use standard Supabase reset flow.

CREATE TABLE IF NOT EXISTS password_reset_requests (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The staff member who needs a reset
  user_id      uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Denormalised for Manager dashboard display (no extra join)
  username     text NOT NULL,
  full_name    text NOT NULL,
  role         text NOT NULL,

  -- Manager responsible for this user
  manager_id   uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  status       text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending', 'approved', 'rejected')),

  reviewed_by  uuid REFERENCES profiles(id) ON DELETE SET NULL,
  reviewed_at  timestamptz,

  created_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE password_reset_requests ENABLE ROW LEVEL SECURITY;

-- Manager sees reset requests for their team
CREATE POLICY "pw_reset_manager_read"
  ON password_reset_requests FOR SELECT
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'manager'
    AND auth.uid() = manager_id
  );

-- Owner sees all
CREATE POLICY "pw_reset_owner_read"
  ON password_reset_requests FOR SELECT
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'owner'
  );

-- Manager can approve/reject
CREATE POLICY "pw_reset_manager_update"
  ON password_reset_requests FOR UPDATE
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'manager'
    AND auth.uid() = manager_id
  );

-- Inserts handled by API route with service role key only


-- ── SECTION 8: HELPER FUNCTION ───────────────────────────────
-- Returns true if a token exists, is unused, and has not expired.
-- Called by POST /api/register/validate before rendering signup form.

CREATE OR REPLACE FUNCTION is_invite_token_valid(p_token text)
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM invite_tokens
    WHERE token      = p_token
      AND used       = false
      AND expires_at > now()
  );
$$ LANGUAGE sql SECURITY DEFINER;


-- ── VERIFY ───────────────────────────────────────────────────
-- SELECT column_name FROM information_schema.columns
-- WHERE table_name = 'profiles'
-- AND column_name IN ('username', 'is_active');
--
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public'
-- AND table_name IN (
--   'invite_tokens', 'pending_registrations', 'password_reset_requests'
-- );
--
-- SELECT conname FROM pg_constraint
-- WHERE conrelid = 'profiles'::regclass
-- AND conname = 'profiles_role_check';
